apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Razib91lightspeed/log-output
    path: overlays/staging
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
